import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;




/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Theatre9.java
 *
 * Created on Oct 14, 2018, 6:19:12 PM
 */

/**
 *
 * @author Guest
 */
public class Theatre7 extends javax.swing.JFrame {

    /** Creates new form Theatre9 */
    public Theatre7() {
        initComponents();
       


    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        Button2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CheckBox1 = new javax.swing.JCheckBox();
        CheckBox2 = new javax.swing.JCheckBox();
        CheckBox3 = new javax.swing.JCheckBox();
        CheckBox4 = new javax.swing.JCheckBox();
        CheckBox5 = new javax.swing.JCheckBox();
        CheckBox6 = new javax.swing.JCheckBox();
        CheckBox7 = new javax.swing.JCheckBox();
        CheckBox9 = new javax.swing.JCheckBox();
        CheckBox8 = new javax.swing.JCheckBox();
        CheckBox10 = new javax.swing.JCheckBox();
        CheckBox11 = new javax.swing.JCheckBox();
        CheckBox14 = new javax.swing.JCheckBox();
        CheckBox13 = new javax.swing.JCheckBox();
        CheckBox12 = new javax.swing.JCheckBox();
        CheckBox15 = new javax.swing.JCheckBox();
        CheckBox17 = new javax.swing.JCheckBox();
        CheckBox16 = new javax.swing.JCheckBox();
        CheckBox18 = new javax.swing.JCheckBox();
        CheckBox19 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CheckBox20 = new javax.swing.JCheckBox();
        CheckBox35 = new javax.swing.JCheckBox();
        CheckBox28 = new javax.swing.JCheckBox();
        CheckBox27 = new javax.swing.JCheckBox();
        CheckBox29 = new javax.swing.JCheckBox();
        CheckBox30 = new javax.swing.JCheckBox();
        CheckBox34 = new javax.swing.JCheckBox();
        CheckBox33 = new javax.swing.JCheckBox();
        CheckBox32 = new javax.swing.JCheckBox();
        CheckBox31 = new javax.swing.JCheckBox();
        CheckBox26 = new javax.swing.JCheckBox();
        CheckBox25 = new javax.swing.JCheckBox();
        CheckBox24 = new javax.swing.JCheckBox();
        CheckBox23 = new javax.swing.JCheckBox();
        CheckBox22 = new javax.swing.JCheckBox();
        CheckBox21 = new javax.swing.JCheckBox();
        CheckBox40 = new javax.swing.JCheckBox();
        CheckBox39 = new javax.swing.JCheckBox();
        CheckBox38 = new javax.swing.JCheckBox();
        CheckBox37 = new javax.swing.JCheckBox();
        CheckBox36 = new javax.swing.JCheckBox();
        CheckBox43 = new javax.swing.JCheckBox();
        CheckBox42 = new javax.swing.JCheckBox();
        CheckBox41 = new javax.swing.JCheckBox();
        CheckBox47 = new javax.swing.JCheckBox();
        CheckBox46 = new javax.swing.JCheckBox();
        CheckBox45 = new javax.swing.JCheckBox();
        CheckBox44 = new javax.swing.JCheckBox();
        CheckBox50 = new javax.swing.JCheckBox();
        CheckBox49 = new javax.swing.JCheckBox();
        CheckBox48 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        Button1 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.activeCaption);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movie Name", "City", "Date", "Time", "Type", "Seats Booked"
            }
        ));
        Table1.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(Table1);

        jLabel6.setFont(new java.awt.Font("Calisto MT", 1, 24)); // NOI18N
        jLabel6.setText("Check the seats booked....");

        Button2.setFont(new java.awt.Font("Andalus", 1, 19)); // NOI18N
        Button2.setText("Check");
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Button2)
                        .addGap(207, 207, 207))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(Button2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);

        jLabel2.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        jLabel2.setText("SELECT SEATS");

        CheckBox1.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox1.setText("A1");
        CheckBox1.setAlignmentX(-1.0F);
        CheckBox1.setAlignmentY(-0.5F);
        CheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CheckBox1ItemStateChanged(evt);
            }
        });
        CheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox1ActionPerformed(evt);
            }
        });

        CheckBox2.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox2.setText("A2");
        CheckBox2.setAlignmentX(-1.0F);
        CheckBox2.setAlignmentY(-0.5F);

        CheckBox3.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox3.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox3.setText("A3");
        CheckBox3.setAlignmentX(-1.0F);
        CheckBox3.setAlignmentY(-0.5F);

        CheckBox4.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox4.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox4.setText("A4");
        CheckBox4.setAlignmentX(-1.0F);
        CheckBox4.setAlignmentY(-0.5F);

        CheckBox5.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox5.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox5.setText("A5");
        CheckBox5.setAlignmentX(-1.0F);
        CheckBox5.setAlignmentY(-0.5F);

        CheckBox6.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox6.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox6.setText("A6");
        CheckBox6.setAlignmentX(-1.0F);
        CheckBox6.setAlignmentY(-0.5F);

        CheckBox7.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox7.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox7.setText("A7");
        CheckBox7.setAlignmentX(-1.0F);
        CheckBox7.setAlignmentY(-0.5F);
        CheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox7ActionPerformed(evt);
            }
        });

        CheckBox9.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox9.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox9.setText("A9");
        CheckBox9.setAlignmentX(-1.0F);
        CheckBox9.setAlignmentY(-0.5F);

        CheckBox8.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox8.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox8.setText("A8");
        CheckBox8.setAlignmentX(-1.0F);
        CheckBox8.setAlignmentY(-0.5F);

        CheckBox10.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox10.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox10.setText("A10");
        CheckBox10.setAlignmentX(-1.0F);
        CheckBox10.setAlignmentY(-0.5F);
        CheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox10ActionPerformed(evt);
            }
        });

        CheckBox11.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox11.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox11.setText("B1");
        CheckBox11.setAlignmentX(-1.0F);
        CheckBox11.setAlignmentY(-0.5F);

        CheckBox14.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox14.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox14.setText("B4");
        CheckBox14.setAlignmentX(-1.0F);
        CheckBox14.setAlignmentY(-0.5F);

        CheckBox13.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox13.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox13.setText("B3");
        CheckBox13.setAlignmentX(-1.0F);
        CheckBox13.setAlignmentY(-0.5F);

        CheckBox12.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox12.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox12.setText("B2");
        CheckBox12.setAlignmentX(-1.0F);
        CheckBox12.setAlignmentY(-0.5F);

        CheckBox15.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox15.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox15.setText("B5");
        CheckBox15.setAlignmentX(-1.0F);
        CheckBox15.setAlignmentY(-0.5F);

        CheckBox17.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox17.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox17.setText("B7");
        CheckBox17.setAlignmentX(-1.0F);
        CheckBox17.setAlignmentY(-0.5F);

        CheckBox16.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox16.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox16.setText("B6");
        CheckBox16.setAlignmentX(-1.0F);
        CheckBox16.setAlignmentY(-0.5F);

        CheckBox18.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox18.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox18.setText("B8");
        CheckBox18.setAlignmentX(-1.0F);
        CheckBox18.setAlignmentY(-0.5F);

        CheckBox19.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox19.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox19.setText("C1");
        CheckBox19.setAlignmentX(-1.0F);
        CheckBox19.setAlignmentY(-0.5F);

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel1.setText("Platinum");

        jLabel3.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel3.setText("     Gold");

        CheckBox20.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox20.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox20.setText("C2");
        CheckBox20.setAlignmentX(-1.0F);
        CheckBox20.setAlignmentY(-0.5F);
        CheckBox20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox20ActionPerformed(evt);
            }
        });

        CheckBox35.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox35.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox35.setText("E1");
        CheckBox35.setAlignmentX(-1.0F);
        CheckBox35.setAlignmentY(-0.5F);
        CheckBox35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox35ActionPerformed(evt);
            }
        });

        CheckBox28.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox28.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox28.setText("D2");
        CheckBox28.setAlignmentX(-1.0F);
        CheckBox28.setAlignmentY(-0.5F);

        CheckBox27.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox27.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox27.setText("D1");
        CheckBox27.setAlignmentX(-1.0F);
        CheckBox27.setAlignmentY(-0.5F);

        CheckBox29.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox29.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox29.setText("D3");
        CheckBox29.setAlignmentX(-1.0F);
        CheckBox29.setAlignmentY(-0.5F);

        CheckBox30.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox30.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox30.setText("D4");
        CheckBox30.setAlignmentX(-1.0F);
        CheckBox30.setAlignmentY(-0.5F);

        CheckBox34.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox34.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox34.setText("D8");
        CheckBox34.setAlignmentX(-1.0F);
        CheckBox34.setAlignmentY(-0.5F);

        CheckBox33.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox33.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox33.setText("D7");
        CheckBox33.setAlignmentX(-1.0F);
        CheckBox33.setAlignmentY(-0.5F);

        CheckBox32.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox32.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox32.setText("D6");
        CheckBox32.setAlignmentX(-1.0F);
        CheckBox32.setAlignmentY(-0.5F);

        CheckBox31.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox31.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox31.setText("D5");
        CheckBox31.setAlignmentX(-1.0F);
        CheckBox31.setAlignmentY(-0.5F);

        CheckBox26.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox26.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox26.setText("C8");
        CheckBox26.setAlignmentX(-1.0F);
        CheckBox26.setAlignmentY(-0.5F);

        CheckBox25.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox25.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox25.setText("C7");
        CheckBox25.setAlignmentX(-1.0F);
        CheckBox25.setAlignmentY(-0.5F);

        CheckBox24.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox24.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox24.setText("C6");
        CheckBox24.setAlignmentX(-1.0F);
        CheckBox24.setAlignmentY(-0.5F);

        CheckBox23.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox23.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox23.setText("C5");
        CheckBox23.setAlignmentX(-1.0F);
        CheckBox23.setAlignmentY(-0.5F);
        CheckBox23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox23ActionPerformed(evt);
            }
        });

        CheckBox22.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox22.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox22.setText("C4");
        CheckBox22.setAlignmentX(-1.0F);
        CheckBox22.setAlignmentY(-0.5F);

        CheckBox21.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox21.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox21.setText("C3");
        CheckBox21.setAlignmentX(-1.0F);
        CheckBox21.setAlignmentY(-0.5F);

        CheckBox40.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox40.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox40.setText("E6");
        CheckBox40.setAlignmentX(-1.0F);
        CheckBox40.setAlignmentY(-0.5F);

        CheckBox39.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox39.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox39.setText("E5");
        CheckBox39.setAlignmentX(-1.0F);
        CheckBox39.setAlignmentY(-0.5F);

        CheckBox38.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox38.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox38.setText("E4");
        CheckBox38.setAlignmentX(-1.0F);
        CheckBox38.setAlignmentY(-0.5F);

        CheckBox37.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox37.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox37.setText("E3");
        CheckBox37.setAlignmentX(-1.0F);
        CheckBox37.setAlignmentY(-0.5F);

        CheckBox36.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox36.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox36.setText("E2");
        CheckBox36.setAlignmentX(-1.0F);
        CheckBox36.setAlignmentY(-0.5F);

        CheckBox43.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox43.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox43.setText("F1");
        CheckBox43.setAlignmentX(-1.0F);
        CheckBox43.setAlignmentY(-0.5F);

        CheckBox42.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox42.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox42.setText("E8");
        CheckBox42.setAlignmentX(-1.0F);
        CheckBox42.setAlignmentY(-0.5F);

        CheckBox41.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox41.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox41.setText("E7");
        CheckBox41.setAlignmentX(-1.0F);
        CheckBox41.setAlignmentY(-0.5F);

        CheckBox47.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox47.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox47.setText("F5");
        CheckBox47.setAlignmentX(-1.0F);
        CheckBox47.setAlignmentY(-0.5F);

        CheckBox46.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox46.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox46.setText("F4");
        CheckBox46.setAlignmentX(-1.0F);
        CheckBox46.setAlignmentY(-0.5F);

        CheckBox45.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox45.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox45.setText("F3");
        CheckBox45.setAlignmentX(-1.0F);
        CheckBox45.setAlignmentY(-0.5F);

        CheckBox44.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox44.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox44.setText("F2");
        CheckBox44.setAlignmentX(-1.0F);
        CheckBox44.setAlignmentY(-0.5F);

        CheckBox50.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox50.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox50.setText("F8");
        CheckBox50.setAlignmentX(-1.0F);
        CheckBox50.setAlignmentY(-0.5F);

        CheckBox49.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox49.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox49.setText("F7");
        CheckBox49.setAlignmentX(-1.0F);
        CheckBox49.setAlignmentY(-0.5F);

        CheckBox48.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox48.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox48.setText("F6");
        CheckBox48.setAlignmentX(-1.0F);
        CheckBox48.setAlignmentY(-0.5F);

        jLabel4.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel4.setText("    Silver");

        jLabel5.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel5.setText("All eyes this way please");

        Button1.setFont(new java.awt.Font("Andalus", 1, 19)); // NOI18N
        Button1.setText("Book the seats");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        Button3.setFont(new java.awt.Font("Andalus", 1, 19)); // NOI18N
        Button3.setText("Proceed");
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CheckBox1)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CheckBox19)
                                        .addComponent(CheckBox11)))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CheckBox2)
                                    .addComponent(CheckBox12)
                                    .addComponent(CheckBox20, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CheckBox35)
                                    .addComponent(CheckBox27)
                                    .addComponent(CheckBox43))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CheckBox28)
                                    .addComponent(CheckBox36)
                                    .addComponent(CheckBox44))))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckBox3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CheckBox21)
                                        .addComponent(CheckBox13))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CheckBox22)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(CheckBox4)
                                            .addComponent(CheckBox14))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CheckBox29)
                                        .addComponent(CheckBox37))
                                    .addGap(10, 10, 10)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CheckBox38)
                                        .addComponent(CheckBox30)
                                        .addComponent(CheckBox46))))
                            .addComponent(CheckBox45))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CheckBox39)
                                    .addComponent(CheckBox47)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CheckBox5)
                                        .addGap(18, 18, 18)
                                        .addComponent(CheckBox6))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CheckBox7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CheckBox23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CheckBox15)
                                    .addComponent(CheckBox31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CheckBox8)
                                .addGap(10, 10, 10)
                                .addComponent(CheckBox9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CheckBox40)
                                    .addComponent(CheckBox48)
                                    .addComponent(CheckBox16))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CheckBox41)
                                        .addComponent(CheckBox49)
                                        .addComponent(CheckBox25)
                                        .addComponent(CheckBox33))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CheckBox17)
                                        .addGap(2, 2, 2))))
                            .addComponent(CheckBox24)
                            .addComponent(CheckBox32))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckBox18)
                            .addComponent(CheckBox26)
                            .addComponent(CheckBox10)
                            .addComponent(CheckBox34)
                            .addComponent(CheckBox42)
                            .addComponent(CheckBox50)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(264, 264, 264))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(234, 234, 234))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(335, 335, 335)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(300, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBox11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox17, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox18, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBox19, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox20, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox21, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox22, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox23, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox24, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox25, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox26, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBox31, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox27, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox28, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox29, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox30, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox32, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox33, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox34, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBox40, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox41, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox35, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox36, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox37, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox38, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox39, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox42, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBox48, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox49, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox43, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox44, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox45, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox46, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox47, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox50, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button3))
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(170, 170, 170)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(414, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(java.awt.Color.darkGray);
        jPanel3.setPreferredSize(new java.awt.Dimension(599, 53));

        jLabel10.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" CARNIVAL CINEMAS ");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 188, 28)));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo1.png"))); // NOI18N
        jLabel13.setText("jLabel12");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(374, 374, 374)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel10)
                .addContainerGap(505, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1265, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   public String movie,date,time,city,type,seat,a1 , a2, a3,a4,a5,a6,a7,a8,a9,a10,b1,b2,b3,b4,b5,b6,b7,b8,c1,c2,c3,c4,c5,c6,c7,c8,d1,d2,d3,d4,d5,d6,d7,d8,e1,e2,e3,e4,e5,e6,e7,e8,f1,f2,f3,f4,f5,f6,f7,f8;
int n;
   private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
   DefaultTableModel model=(DefaultTableModel)Table1.getModel();

       try{
      Class.forName("java.sql.Driver");
      Connection con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","dhruvi");
      Statement stmt=con.createStatement();
      String q1="Select * from movie;";
      ResultSet rs=stmt.executeQuery(q1);
      if(rs.last()){
       movie=rs.getString("Movie_name");
       date=rs.getString("Date");
       time=rs.getString("Time");
       city=rs.getString("City");
       type=rs.getString("Type");
       n=rs.getInt("Seats");
      }

 }catch(Exception e){
     JOptionPane.showMessageDialog(null,"ERROR: "+e);
 }

      try{
    
      Connection con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","dhruvi");
      Statement stmt=con.createStatement();
      String q1="Select * from t1 where Movie_Name='"+movie+"' and city='"+city+"' and date='"+date+"' and time='"+time+"' and type='"+type+"';";

      ResultSet rs=stmt.executeQuery(q1);
      while(rs.next()){
      String a=rs.getString("Movie_Name");
      String b=rs.getString("City");  
      String c=rs.getString("Date");
      String d=rs.getString("Time");
      String e=rs.getString("Type");
      String f=rs.getString("Seat_No");
      model.addRow(new Object[] {a,b,c,d,e,f});
      }
     
 }catch(Exception e){
     JOptionPane.showMessageDialog(null,"ERROR: "+e);
 }




}//GEN-LAST:event_Button2ActionPerformed

    private void CheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CheckBox1ItemStateChanged
        // TODO add your handling code here

    }//GEN-LAST:event_CheckBox1ItemStateChanged

    private void CheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_CheckBox1ActionPerformed

    private void CheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox7ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_CheckBox7ActionPerformed

    private void CheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox10ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_CheckBox10ActionPerformed

    private void CheckBox20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox20ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_CheckBox20ActionPerformed

    private void CheckBox35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox35ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_CheckBox35ActionPerformed

    private void CheckBox23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox23ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_CheckBox23ActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
  if(CheckBox1.isSelected())
      a1="A1,";
  else
      a1="";
   if(CheckBox2.isSelected())
      a2="A2,";
  else
      a2="";
    if(CheckBox3.isSelected())
      a3="A3,";
  else
      a3="";
   if(CheckBox4.isSelected())
      a4="A4,";
  else
      a4="";
    if(CheckBox5.isSelected())
      a5="A5,";
  else
      a5="";
   if(CheckBox6.isSelected())
      a6="A6,";
  else
      a6="";
    if(CheckBox7.isSelected())
      a7="A7,";
  else
      a7="";
   if(CheckBox8.isSelected())
      a8="A8,";
  else
      a8="";
    if(CheckBox9.isSelected())
      a9="A9,";
  else
      a9="";
   if(CheckBox10.isSelected())
      a10="A10,";
  else
      a10="";
    if(CheckBox11.isSelected())
      b1="B1,";
  else
      b1="";
   if(CheckBox12.isSelected())
      b2="B2,";
  else
      b2="";
    if(CheckBox13.isSelected())
      b3="B3,";
  else
      b3="";
   if(CheckBox14.isSelected())
      b4="B4,";
  else
      b4="";
    if(CheckBox15.isSelected())
      b5="B5,";
  else
      b5="";
   if(CheckBox16.isSelected())
      b6="B6,";
  else
      b6="";
    if(CheckBox17.isSelected())
      b7="B7,";
  else
      b7="";
   if(CheckBox18.isSelected())
      b8="B8,";
  else
      b8="";
    if(CheckBox19.isSelected())
      c1="C1,";
  else
      c1="";
   if(CheckBox20.isSelected())
      c2="C2,";
  else
      c2="";
    if(CheckBox21.isSelected())
      c3="C3,";
  else
     c3="";
   if(CheckBox22.isSelected())
      c4="C4,";
  else
      c4="";
    if(CheckBox23.isSelected())
      c5="C5,";
  else
      c5="";
   if(CheckBox24.isSelected())
      c6="C6,";
  else
      c6="";
    if(CheckBox25.isSelected())
      c7="C7,";
  else
      c7="";
   if(CheckBox26.isSelected())
      c8="C8,";
  else
      c8="";
  if(CheckBox27.isSelected())
      d1="D1,";
  else
      d1="";
   if(CheckBox28.isSelected())
      d2="D2,";
  else
      d2="";
    if(CheckBox29.isSelected())
      d3="D3,";
  else
      d3="";
   if(CheckBox30.isSelected())
      d4="D4,";
  else
      d4="";
  if(CheckBox31.isSelected())
      d5="D5,";
  else
      d5="";
   if(CheckBox32.isSelected())
      d6="D6,";
  else
      d6="";
  if(CheckBox33.isSelected())
      d7="D7,";
  else
      d7="";
   if(CheckBox34.isSelected())
      d8="D8,";
  else
      d8="";
  if(CheckBox35.isSelected())
      e1="E1,";
  else
      e1="";
   if(CheckBox36.isSelected())
      e2="E2,";
  else
      e2="";
    if(CheckBox37.isSelected())
      e3="E3,";
  else
      e3="";
   if(CheckBox38.isSelected())
      e4="E4,";
  else
      e4="";
  if(CheckBox39.isSelected())
      e5="E5,";
  else
      e5="";
   if(CheckBox40.isSelected())
      e6="E6,";
  else
      e6="";
  if(CheckBox41.isSelected())
      e7="E7,";
  else
      e7="";
   if(CheckBox42.isSelected())
      e8="E8,";
  else
      e8="";
  if(CheckBox43.isSelected())
      f1="F1,";
  else
      f1="";
   if(CheckBox44.isSelected())
      f2="F2,";
  else
      f2="";
    if(CheckBox45.isSelected())
      f3="F3,";
  else
      f3="";
   if(CheckBox46.isSelected())
      f4="F4,";
  else
      f4="";
  if(CheckBox47.isSelected())
      f5="F5,";
  else
      f5="";
   if(CheckBox48.isSelected())
      f6="F6,";
  else
      f6="";
  if(CheckBox49.isSelected())
      f7="F7,";
  else
      f7="";
   if(CheckBox50.isSelected())
      f8="F8,";
  else
      f8="";

 seat=a1+a2+a3+a4+a5+a6+a7+a8+a9+a10+b1+b2+b3+b4+b5+b6+b7+b8+c1+c2+c3+c4+c5+c6+c7+c8+d1+d2+d3+d4+d5+d6+d7+d8+e1+e2+e3+e4+e5+e6+e7+e8+f1+f2+f3+f4+f5+f6+f7+f8;

 try{
      Class.forName("java.sql.Driver");
      Connection con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","dhruvi");
      Statement stmt=con.createStatement();
      String q1="Select * from movie;";
      ResultSet rs=stmt.executeQuery(q1);
      if(rs.last()){
       movie=rs.getString("Movie_name");
       date=rs.getString("Date");
       time=rs.getString("Time");
       city=rs.getString("City");
       type=rs.getString("Type");
      }

 }catch(Exception e){
     JOptionPane.showMessageDialog(null,"ERROR: "+e);
 }

try{
      Class.forName("java.sql.Driver");
      Connection con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","dhruvi");
      Statement stmt=con.createStatement();
      String q2="Insert into t1 values('"+movie+"','"+city+"','"+date+"','"+time+"','"+type+"','"+seat+"');";
       stmt.executeUpdate(q2);
      JOptionPane.showMessageDialog(null,"Seats Booked Successfully");


 }catch(Exception e){
     JOptionPane.showMessageDialog(null,"ERROR: "+e);
 }



}//GEN-LAST:event_Button1ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
       
       this.setVisible(false);
        Theatre6 frame = new Theatre6();
        frame.setVisible(true);

}//GEN-LAST:event_Button3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

       try{
      Class.forName("java.sql.Driver");
      Connection con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","dhruvi");
      Statement stmt=con.createStatement();
      String q1="Select * from movie;";
      ResultSet rs=stmt.executeQuery(q1);
      if(rs.last()){
       type=rs.getString("Type");
       n=rs.getInt("Seats");
      }

 }catch(Exception e){
     JOptionPane.showMessageDialog(null,"ERROR: "+e);
 }
    JOptionPane.showMessageDialog(null,"Please book "+n+" seats of type "+type+" after checking the seats already booked. ");
           

    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Theatre7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JCheckBox CheckBox1;
    private javax.swing.JCheckBox CheckBox10;
    private javax.swing.JCheckBox CheckBox11;
    private javax.swing.JCheckBox CheckBox12;
    private javax.swing.JCheckBox CheckBox13;
    private javax.swing.JCheckBox CheckBox14;
    private javax.swing.JCheckBox CheckBox15;
    private javax.swing.JCheckBox CheckBox16;
    private javax.swing.JCheckBox CheckBox17;
    private javax.swing.JCheckBox CheckBox18;
    private javax.swing.JCheckBox CheckBox19;
    private javax.swing.JCheckBox CheckBox2;
    private javax.swing.JCheckBox CheckBox20;
    private javax.swing.JCheckBox CheckBox21;
    private javax.swing.JCheckBox CheckBox22;
    private javax.swing.JCheckBox CheckBox23;
    private javax.swing.JCheckBox CheckBox24;
    private javax.swing.JCheckBox CheckBox25;
    private javax.swing.JCheckBox CheckBox26;
    private javax.swing.JCheckBox CheckBox27;
    private javax.swing.JCheckBox CheckBox28;
    private javax.swing.JCheckBox CheckBox29;
    private javax.swing.JCheckBox CheckBox3;
    private javax.swing.JCheckBox CheckBox30;
    private javax.swing.JCheckBox CheckBox31;
    private javax.swing.JCheckBox CheckBox32;
    private javax.swing.JCheckBox CheckBox33;
    private javax.swing.JCheckBox CheckBox34;
    private javax.swing.JCheckBox CheckBox35;
    private javax.swing.JCheckBox CheckBox36;
    private javax.swing.JCheckBox CheckBox37;
    private javax.swing.JCheckBox CheckBox38;
    private javax.swing.JCheckBox CheckBox39;
    private javax.swing.JCheckBox CheckBox4;
    private javax.swing.JCheckBox CheckBox40;
    private javax.swing.JCheckBox CheckBox41;
    private javax.swing.JCheckBox CheckBox42;
    private javax.swing.JCheckBox CheckBox43;
    private javax.swing.JCheckBox CheckBox44;
    private javax.swing.JCheckBox CheckBox45;
    private javax.swing.JCheckBox CheckBox46;
    private javax.swing.JCheckBox CheckBox47;
    private javax.swing.JCheckBox CheckBox48;
    private javax.swing.JCheckBox CheckBox49;
    private javax.swing.JCheckBox CheckBox5;
    private javax.swing.JCheckBox CheckBox50;
    private javax.swing.JCheckBox CheckBox6;
    private javax.swing.JCheckBox CheckBox7;
    private javax.swing.JCheckBox CheckBox8;
    private javax.swing.JCheckBox CheckBox9;
    private javax.swing.JTable Table1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
